parameters:
    pim_data_generator.generator.class : Pim\Bundle\DataGeneratorBundle\Generator\Generator
    pim_data_generator.generator.currency.class : Pim\Bundle\DataGeneratorBundle\Generator\CurrencyGenerator
    pim_data_generator.generator.channel.class : Pim\Bundle\DataGeneratorBundle\Generator\ChannelGenerator
    pim_data_generator.generator.attribute.class : Pim\Bundle\DataGeneratorBundle\Generator\AttributeGenerator
#    pim_data_generator.generator.attribute_option.class : Pim\Bundle\DataGeneratorBundle\Generator\AttributeOptionGenerator
    pim_data_generator.generator.family.class : Pim\Bundle\DataGeneratorBundle\Generator\FamilyGenerator
    pim_data_generator.generator.product.class : Pim\Bundle\DataGeneratorBundle\Generator\ProductGenerator

services:
    pim_data_generator.generator:
        class: %pim_data_generator.generator.class%
        arguments:
            - @pim_data_generator.generator.currency
            - @pim_data_generator.generator.channel
            - @pim_data_generator.generator.attribute
            - @pim_data_generator.generator.family
            - @pim_data_generator.generator.product

    pim_data_generator.generator.currency:
        class: %pim_data_generator.generator.currency.class%

    pim_data_generator.generator.channel:
        class: %pim_data_generator.generator.channel.class%

    pim_data_generator.generator.attribute:
        class: %pim_data_generator.generator.attribute.class%
        arguments:
            - '@pim_catalog.repository.attribute_group'
            - '@pim_catalog.repository.locale'
            - '@pim_catalog.registry.attribute_type'

    pim_data_generator.generator.family:
        class: %pim_data_generator.generator.family.class%
        arguments:
            - @pim_catalog.repository.channel
            - @pim_catalog.repository.locale

#    pim_data_generator.generator.attribute_option:
#        class: pim_data_generator.generator.attribute.class
#        arguments:
#            - @pim_catalog.repository.family
#            - @pim_catalog.repository.attribute
#            - @pim_catalog.repository.channel
#            - @pim_catalog.repository.locale
#
    pim_data_generator.generator.product:
        class: %pim_data_generator.generator.product.class%
        arguments:
            - '@pim_catalog.repository.family'
            - '@pim_catalog.repository.attribute'
            - '@pim_catalog.repository.channel'
            - '@pim_catalog.repository.locale'
            - '@pim_catalog.repository.currency'
            - '@pim_catalog.repository.category'

