jobs:
    update_product_value:
        connector: Akeneo Mass Edit Connector
        alias:     update_product_value
        label:     Mass update products
        type:      mass_edit
    add_product_value:
        connector: Akeneo Mass Edit Connector
        alias:     add_product_value
        label:     Mass add products values
        type:      mass_edit
    edit_common_attributes:
        connector: Akeneo Mass Edit Connector
        alias:     edit_common_attributes
        label:     Mass edit common product attributes
        type:      mass_edit
    set_attribute_requirements:
        connector: Akeneo Mass Edit Connector
        alias:     set_attribute_requirements
        label:     Set family attribute requirements
        type:      mass_edit
    add_to_variant_group:
        connector: Akeneo Mass Edit Connector
        alias:     add_to_variant_group
        label:     Mass add products to variant group
        type:      mass_edit
    csv_product_quick_export:
        connector: Akeneo Mass Edit Connector
        alias: csv_product_quick_export
        label: CSV product quick export
        type: quick_export
        configuration:
            delimiter:  ;
            enclosure:  '"'
            withHeader: true
            filePath:   /tmp/products_export_%locale%_%scope%_%datetime%.csv
    category_import:
        connector: Akeneo Native Connector
        alias:     csv_category_import
        label:     Category import
        type:      import
        configuration:
            uploadAllowed:       true
            delimiter:           ;
            enclosure:           '"'
            escape:              '\'
            circularRefsChecked: true
    category_export:
        connector: Akeneo Native Connector
        alias:     csv_category_export
        label:     Category export
        type:      export
        configuration:
            delimiter:  ;
            enclosure:  '"'
            withHeader: true
            filePath: /tmp/category.csv
    association_type_import:
        connector: Akeneo Native Connector
        alias:     csv_association_type_import
        label:     Association type import
        type:      import
        configuration:
            uploadAllowed: true
            delimiter:     ;
            enclosure:     '"'
            escape:        '\'
    association_type_export:
        connector: Akeneo Native Connector
        alias:     csv_association_type_export
        label:     Association type export
        type:      export
        configuration:
            delimiter:  ;
            enclosure:  '"'
            withHeader: true
            filePath: /tmp/association-type.csv
    group_import:
        connector: Akeneo Native Connector
        alias:     csv_group_import
        label:     Group import
        type:      import
        configuration:
            uploadAllowed: true
            delimiter:     ;
            enclosure:     '"'
            escape:        '\'
    group_export:
        connector: Akeneo Native Connector
        alias:     csv_group_export
        label:     Group export
        type:      export
        configuration:
            delimiter:  ;
            enclosure:  '"'
            withHeader: true
            filePath: /tmp/group.csv
    attribute_import:
        connector: Akeneo Native Connector
        alias:     csv_attribute_import
        label:     Attribute import
        type:      import
        configuration:
            uploadAllowed: true
            delimiter:     ;
            enclosure:     '"'
            escape:        '\'
    attribute_export:
        connector: Akeneo Native Connector
        alias:     csv_attribute_export
        label:     Attribute export
        type:      export
        configuration:
            delimiter:  ;
            enclosure:  '"'
            withHeader: true
            filePath: /tmp/attribute.csv
    option_import:
        connector: Akeneo Native Connector
        alias:     csv_attribute_option_import
        label:     Option import
        type:      import
        configuration:
            uploadAllowed: true
            delimiter:     ;
            enclosure:     '"'
            escape:        '\'
    option_export:
        connector: Akeneo Native Connector
        alias:     csv_attribute_option_export
        label:     Option export
        type:      export
        configuration:
            delimiter:  ;
            enclosure:  '"'
            withHeader: true
            filePath: /tmp/attribute-option.csv
