jobs:
    update_product_value:
        connector: Akeneo Mass Edit Connector
        alias:     update_product_value
        label:     Mass update products
        type:      mass_edit
    add_product_value:
        connector: Akeneo Mass Edit Connector
        alias:     add_product_value
        label:     Mass add products values
        type:      mass_edit
    edit_common_attributes:
        connector: Akeneo Mass Edit Connector
        alias:     edit_common_attributes
        label:     Mass edit common product attributes
        type:      mass_edit
    set_attribute_requirements:
        connector: Akeneo Mass Edit Connector
        alias:     set_attribute_requirements
        label:     Set family attribute requirements
        type:      mass_edit
    add_to_variant_group:
        connector: Akeneo Mass Edit Connector
        alias:     add_to_variant_group
        label:     Mass add products to variant group
        type:      mass_edit
    csv_product_quick_export:
        connector: Akeneo Mass Edit Connector
        alias: csv_product_quick_export
        label: CSV product quick export
        type: quick_export
        configuration:
            delimiter:  ;
            enclosure:  '"'
            withHeader: true
            filePath:   /tmp/products_export_%locale%_%scope%_%datetime%.csv
    rule_import:
        connector: Akeneo Rule Engine Connector
        alias:     yml_rule_import
        label:     Rule import
        type:      import
        configuration:
            uploadAllowed: true
    rule_export:
        connector: Akeneo Rule Engine Connector
        alias:     yml_rule_export
        label:     Rule export
        type:      export
        configuration:
            header: rules
    category_import:
        connector: Akeneo Native Connector
        alias:     csv_category_import
        label:     Category import
        type:      import
        configuration:
            uploadAllowed:       true
            delimiter:           ;
            enclosure:           '"'
            escape:              '\'
            circularRefsChecked: true
    category_export:
        connector: Akeneo Native Connector
        alias:     csv_category_export
        label:     Category export
        type:      export
        configuration:
            delimiter:  ;
            enclosure:  '"'
            withHeader: true
            filePath: /tmp/category.csv
    association_type_import:
        connector: Akeneo Native Connector
        alias:     csv_association_type_import
        label:     Association type import
        type:      import
        configuration:
            uploadAllowed: true
            delimiter:     ;
            enclosure:     '"'
            escape:        '\'
    association_type_export:
        connector: Akeneo Native Connector
        alias:     csv_association_type_export
        label:     Association type export
        type:      export
        configuration:
            delimiter:  ;
            enclosure:  '"'
            withHeader: true
            filePath: /tmp/association-type.csv
    group_import:
        connector: Akeneo Native Connector
        alias:     csv_group_import
        label:     Group import
        type:      import
        configuration:
            uploadAllowed: true
            delimiter:     ;
            enclosure:     '"'
            escape:        '\'
    group_export:
        connector: Akeneo Native Connector
        alias:     csv_group_export
        label:     Group export
        type:      export
        configuration:
            delimiter:  ;
            enclosure:  '"'
            withHeader: true
            filePath: /tmp/group.csv
    attribute_import:
        connector: Akeneo Native Connector
        alias:     csv_attribute_import
        label:     Attribute import
        type:      import
        configuration:
            uploadAllowed: true
            delimiter:     ;
            enclosure:     '"'
            escape:        '\'
    attribute_export:
        connector: Akeneo Native Connector
        alias:     csv_attribute_export
        label:     Attribute export
        type:      export
        configuration:
            delimiter:  ;
            enclosure:  '"'
            withHeader: true
            filePath: /tmp/attribute.csv
    option_import:
        connector: Akeneo Native Connector
        alias:     csv_attribute_option_import
        label:     Option import
        type:      import
        configuration:
            uploadAllowed: true
            delimiter:     ;
            enclosure:     '"'
            escape:        '\'
    option_export:
        connector: Akeneo Native Connector
        alias:     csv_attribute_option_export
        label:     Option export
        type:      export
        configuration:
            delimiter:  ;
            enclosure:  '"'
            withHeader: true
            filePath: /tmp/attribute-option.csv
    product_proposal_import:
        connector: Akeneo Native Connector
        alias:     csv_product_proposal_import
        label:     Demo product draft import
        type:      import
        configuration:
            uploadAllowed:    true
            multiple:         false
            delimiter:        ;
            enclosure:        '"'
            escape:           '\'
            enabled:          true
            decimalSeparator: .
            dateFormat:       mm/dd/yyyy
    add_product_value_with_permission:
        connector: Akeneo Mass Edit Connector
        alias:     add_product_value_with_permission
        label:     Mass add products values with permission check
        type:      mass_edit
    update_product_value_with_permission:
        connector: Akeneo Mass Edit Connector
        alias:     update_product_value_with_permission
        label:     Mass update products values with permission check
        type:      mass_edit
    publish_product:
        connector: Akeneo Mass Edit Connector
        alias:     publish_product
        label:     Mass publish products
        type:      mass_edit
    unpublish_product:
        connector: Akeneo Mass Edit Connector
        alias:     unpublish_product
        label:     Mass unpublish products
        type:      mass_edit
    edit_common_attributes_with_permission:
        connector: Akeneo Mass Edit Connector
        alias:     edit_common_attributes_with_permission
        label:     Mass edit common product attributes with permission check
        type:      mass_edit
    approve_product_draft:
        connector: Akeneo Native Connector
        alias:     approve_product_draft
        label:     Mass approve product drafts
        type:      mass_edit
    refuse_product_draft:
        connector: Akeneo Native Connector
        alias:     refuse_product_draft
        label:     Mass reject product drafts
        type:      mass_edit
    asset_import:
        connector: Akeneo Product Asset Connector
        alias:     csv_asset_import
        label:     Demo asset import
        type:      import
        configuration:
            filePath:      /tmp/assets.csv
            uploadAllowed: true
            delimiter:     ;
            enclosure:     '"'
            escape:        '\'
    asset_category_export:
        connector: Akeneo Product Asset Connector
        alias:     csv_asset_category_export
        label:     Asset category export
        type:      export
        configuration:
            delimiter:  ;
            enclosure:  '"'
            withHeader: true
            filePath: /tmp/asset-category.csv
    asset_export:
        connector: Akeneo Product Asset Connector
        alias:     csv_asset_export
        label:     Asset export
        type:      export
        configuration:
            delimiter:  ;
            enclosure:  '"'
            withHeader: true
            filePath: /tmp/asset.csv
    asset_variation_export:
        connector: Akeneo Product Asset Connector
        alias:     csv_asset_variation_export
        label:     Asset export
        type:      export
        configuration:
            delimiter:  ;
            enclosure:  '"'
            withHeader: true
            filePath: /tmp/asset-variation.csv
    asset_category_import:
        connector: Akeneo Product Asset Connector
        alias:     csv_asset_category_import
        label:     Demo asset category import
        type:      import
        configuration:
            filePath:      /tmp/assets-categories.csv
            uploadAllowed: true
            delimiter:     ;
            enclosure:     '"'
            escape:        '\'
    asset_channel_configuration_import:
        connector: Akeneo Product Asset Connector
        alias:     yml_asset_channel_configuration_import
        label:     Demo asset channel configuration import
        type:      import
        configuration:
            uploadAllowed: true
    asset_channel_configuration_export:
        connector: Akeneo Product Asset Connector
        alias: yml_asset_channel_configuration_export
        label: Demo asset channel configuration export
        type: export
        configuration:
            filePath:      /tmp/asset_channel_configurations.yml
            uploadAllowed: true
            multiple:
            header: asset_channel_configurations
    apply_assets_mass_upload:
        connector: Akeneo Product Asset Connector
        alias:     apply_assets_mass_upload
        label:     Mass approve product drafts
        type:      mass_upload
