language: php
php:
    - "5.4"
    - "5.5"
    - "5.6"
    - "7.0"
    - "hhvm"

# Allow to use container infrastructure
sudo: false

cache:
  directories:
    - $HOME/.composer/cache/files

before_install:
    - if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then
        phpenv config-rm xdebug.ini;
      fi
    - echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
    - composer self-update --no-interaction

install:
    - composer update --prefer-dist --no-interaction
    - curl http://get.sensiolabs.org/php-cs-fixer.phar -o php-cs-fixer

script:
    - bin/phpspec run
    - php php-cs-fixer fix --dry-run -v --diff --config-file=.php_cs.php


notifications:
  slack: akeneo:fDZaQeRRj1gVtXCW3f2kQAxo
